Feature/primera entrega
inakitrapiella/ProgWeb_1 pull request #1
Opened 2024-08-20 18:51 UTC by inakitrapiella

Hola profe, como esta? 

Cree esta maqueta de una hamburguesería, le agregue además una imagen. Además cree un header, un main con secciones adentro y al final agregue un foteer.

Espero le guste.

2024-08-20 21:15 UTC, MVelasquez98 requested changes
Falta el archivo readme.md. Laconsigna solicita:
"Antes de iniciar con el desarrollo del proyecto, es fundamental proporcionar una descripción detallada del mismo en el archivo [README.md](https://docs.github.com/es/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes) de tu repositorio en GitHub. Este archivo actúa como la primera impresión del proyecto para cualquier persona que visite el repositorio, por lo que debe ser claro, conciso y completo"

2024-08-20 21:15 UTC, MVelasquez98 commented on index.html
>      <title>Document</title>
Es title corresponde al titulo que se ve en el encabezado de la pestaña del navegador. No corresponde "document", tiene que ser un nombre descriptivo del sitio

2024-08-20 21:15 UTC, MVelasquez98 commented on index.html
> +            <h2>Contacto</h2>
La actividad solicita:
"Incluye elementos básicos como título, párrafos, imágenes, enlaces, listas, formularios y tablas relacionados con tu tema."
Falta utilizar formularios, que bien podría usarse aca un formulario de contacto por ejemplo

2024-08-20 21:15 UTC, MVelasquez98 commented on index.html
> +        <section id="menu">
La actividad solicita:
"Incluye elementos básicos como título, párrafos, imágenes, enlaces, listas, formularios y tablas relacionados con tu tema."
Falta utilizar tablas, que bien podría usarse aca una tabala de productos/precios por ejemplo

2024-08-20 21:22 UTC, MVelasquez98 requested changes
PUNTAJE POR CONSIGNA:
1. Estructura HTML (3 puntos):
   -  Uso correcto de HTML5 para estructurar la página. :heavy_check_mark:
   - Completa inclusión de elementos básicos como título, párrafos, imágenes, enlaces, listas y tablas relacionados con el tema elegido. :x:
    - Introduce etiquetas semánticas pertinentes para mejorar la accesibilidad y el SEO. :heavy_check_mark:
2. GitHub (5 puntos):
    - Correcta creación de ramas "master" y "develop" en el repositorio.  :x: La rama que se creo es main, no master
  - Creación de una rama "feature/primera-entrega" y habilitación de GitHub Pages para esa rama. :heavy_check_mark:
   - Realización de commits necesarios sobre la rama de desarrollo. :heavy_check_mark:
   - Correcta creación de la pull request contra la rama "develop". :heavy_check_mark:
   - Entrega de la URL de la pull request y la URL generada por GitHub Pages. :heavy_check_mark:

3. Documentación (2 puntos):
   - Inclusión de comentarios claros y concisos en el código HTML. :x: 
  - Realizar una descripción y overview del proyecto elegido en el readme.md del repositorio :x: 
  
 Nota: 6 (Seis)

2024-09-13 02:08 UTC, inakitrapiella commented
@MVelasquez98  cambios realizados, solicito revisión

2024-09-13 21:11 UTC, MVelasquez98 approved these changes
LGTM
Ojo de todas formas que tenes conflictos de Git en el readme.md,
Antes de hacer **rebase and merge** revisa la [documentación](https://docs.github.com/es/enterprise-cloud@latest/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) al respecto para que no se te pisen los cambios.

2024-09-14 00:03 UTC, inakitrapiella commented
@MVelasquez98  buenas tardes resolvi los conflictos en el readme pero no me deja hacer el rebase and merge por que me dice que tengo conflictos pero no me muestra cuales. Si me podria ayudar le agradeceria un monton.

2024-09-14 01:57 UTC, MVelasquez98 commented
Lo más facil es:
- En tu local cambiate a la rama develop y hace pull (asi te aseguras que tenes lo ultimo de develop primero)
- Volve a tu rama "feature/primera-entrega"
- En vsCode control de versiones->...->en rama->fusionar cambios mediante rebase
<img width="986" alt="image" src="https://github.com/user-attachments/assets/95719609-8dd2-4f76-950a-6aa9af615eb4">
- Selecciona develop
<img width="614" alt="image" src="https://github.com/user-attachments/assets/367ed046-aa50-49a0-b654-900caf5fdb66">
- ahi ya te van aparecer los archivos con conflicto (debería ser solo el readme) marcados en rojo. Entras al archivo y selcciona cuales son los cambios que queres conservar y cuales no. Te van aparecer botones de cambio entrante y cambio local ( para ver cual de los dos queres conservar). Esos son justamente los conflictos, capaz en develop no tenias un espacio que ahora si, y git no sabe que queres hacer, por eso te pregunta.
- Le das guardar
-  corres git add .
- Le das en "Continuar" 
- corres git push (o a veces es necesario git push -f)

2024-09-14 02:08 UTC, MVelasquez98 commented
Capaz te sirven para entender el concepto
[Cómo resolver conflictos de versiones con VS Code](https://youtu.be/g7bbxEt09PI?si=sg-c0xIGOCFpHzCc)
[Curso de VSCode & Git | Como Solucionar un Merge Conflict (Conflicto de Merge) En VSCode Versión 1
](https://youtu.be/uDDNwwxoaZY?si=N2-WR1iDDhs_7rBj)

2024-09-16 22:21 UTC, merged