Release/primer parcial
inakitrapiella/ProgWeb_1 pull request #3
Opened 2024-10-02 20:13 UTC by inakitrapiella

Hola profesor, le hago entrega de mi primer parcial en donde integre un carousel, además de agregar el iframe y las columnas de boostrap. Espero le guste.

2024-10-04 19:19 UTC, MVelasquez98 requested changes
PUNTAJE POR CONSIGNA:
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

Incorporación de Componentes Avanzados de HTML (1 punto):

✅ Agregar al menos un componente avanzado de HTML a la página, como un iframe de un video de YouTube o un mapa de Google Maps. (1 punto).
Implementación de Bootstrap para Diseño Responsivo (5 puntos):

✅ Instalar la biblioteca Bootstrap en el proyecto. (1 punto)
❌ Utilizar el sistema de columnas de Bootstrap para hacer que el sitio sea más responsivo en dispositivos móviles. (3 puntos). Podría aprovecharse mejor el [sistema de columnas en Bootstrap](https://getbootstrap.esdocu.com/docs/5.1/layout/columns/) o [grilla](https://getbootstrap.com/docs/4.0/layout/grid/) para mejorar el [Diseño UI](https://perio.unlp.edu.ar/catedras/comyddhhlic/wp-content/uploads/sites/125/2023/02/Diseno-UX-UI.pdf), más que nada en dispositivos moviles.
⚠️ Incluir al menos un componente avanzado de Bootstrap, como un carrusel, una barra de navegación o un modal. (1 punto). No esta funcionando correctamente el navbar en dispositivos moviles.
Gestión del Proyecto con GitHub (4 puntos):

✅ Realización de commits necesarios sobre la rama de desarrollo utilizando Git. (1 punto)
✅ Creación de una rama "release/primer-parcial" a partir de la rama "develop" utilizando Git. (1 punto)
❌ Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "feature/segunda-entrega" con "develop" en GitHub. (1 punto). Tene cuidado en las proxima entregas de donde estas posicionada a la hora de hacer push de un commit, respeta las pull request para subir los cambios. Para evitar conflictos de merge siempre asegurarte de tener los últimos cambios de develop antes de crear la rama de trabajo.
✅ Proporcionar la URL de la pull request y la URL generada por GitHub Pages para la rama "release/primer-parcial" como parte de la entrega. (1 punto)
Nota: 5 (Cinco)

2024-10-04 19:19 UTC, MVelasquez98 commented on index.html
> +        <nav class="container-fluid">
Quizas podrías usar un componente de Bootstrap [navbar](https://getbootstrap.com/docs/4.0/components/navbar/) aca. Para evitar que se vea así en dispositivos moviles.
![image](https://github.com/user-attachments/assets/beb242c5-91da-4b6d-bdd8-f386aa8bdb6d)
Con este componente el menu se vuelve responsive.
![image](https://github.com/user-attachments/assets/37ddc2c1-31cc-456b-83bd-c7bb9af0a774)

2024-10-04 19:19 UTC, MVelasquez98 commented on index.html
> +            <iframe width="560" height="315" src="https://www.youtube.com/embed/RKWLu6UHryQ?si=mq28iAbQmArE8_bF" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard
El video no se ve responsivo en dispositivos moviles:
![image](https://github.com/user-attachments/assets/bc685665-6de2-4c1f-921f-b30eaea946df)
Bootstrap te facilita los errores que se puedan generar con los [embed](https://getbootstrap.com/docs/4.0/utilities/embed/) de forma responsiva.

2024-10-20 01:04 UTC, inakitrapiella commented
Hola profesor ya realice los cambios a mi código, solicito el LGTM para poder entregar mi trabajo, espero este bien.
@MVelasquez98

2024-10-20 17:32 UTC, MVelasquez98 approved these changes
LGTM
Ojo revisa que no esta resuelto lo del navbar, arreglalo en la tercera entrega, no estas usando el componente de bootstrap:
![image](https://github.com/user-attachments/assets/5e8329c2-f8e7-468b-9f85-bf4055db97d6)

2024-10-21 02:14 UTC, merged