agregue cambios para act 3
inakitrapiella/ProgWeb_1 pull request #5
Opened 2024-10-21 03:59 UTC by inakitrapiella

Agregue todo los solicitado para la entrega 3 y arregle el navbar.

2024-10-24 18:59 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

- **Algoritmos (1 punto)**
✅ 1 punto: Uso correcto y eficiente de algoritmos condicionales y ciclos.

- **Funciones (1 punto)**
✅ 1 punto: Funciones con nombres claros, estructura correcta y resultados correctos.

- **Funcionalidad (1 punto)**
❌  0 puntos: Flujo de trabajo incompleto o funcionalidad inapropiada al contexto. Tu algoritmo principal no termina de resolver algo funcional para la pagina, solo hay un pedido de cantidad, que calcula un descuento a partir de un precio estatico; y una validación de formulario (que utiliza eventos y DOM que no vimos en la unidad y no entra en esta entrega) que hace validaciones que se pueden solucionar con una etiqueta [required](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required) en HTML simplemente. Se espera algun algoritmo relacionado con calcular un precio, filtrar o buscar productos, armar un carrito de compras, etc. Se tiene que avanzar más sobre la idea pensada de pedir hamburguesas, quizas ir preguntando al usuario las opciones, aditivos, bebdidas, etc.

- **Interactividad (1 punto)**
⚠️ 0.5 puntos: Interactividad insuficiente o salidas incoherentes. Hay un solo prompt pidiendo la cantidad, el resto de entradas son con DOM, que no entra en esta entrega.

- **Escalabilidad (1 punto)**
⚠️ 0.5 puntos:  No utilizas clases ni métodos.

- **Legibilidad (1 punto)**
⚠️ 0.5 puntos: Nombres de variables, funciones u objetos poco significativos, código ilegible o mal estructurado. Cuesta seguir el hilo de cual es la funcionalidad que estas buscando, seprar correctamente las clases en archivos separaos y definir correctamente las funciones en el orden que corresponde te va ayudar a ordenar más el archivo.

- **GitHub (4 puntos):**
✅ 1 punto: Creación de una rama "backport/primer-parcial" a partir de la rama "master" utilizando Git.
✅ 1 punto: Creación de una rama "feature/tercera-entrega" a partir de la rama "develop" utilizando Git.
✅ 1 punto: Correcta realización de la solicitud de revisión para fusionar la rama "backport/primer-parcial" con "develop" en GitHub, resolviendo los conflictos de merge (si fuese necesario).
✅ 1 punto: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "release/primer-parcial" con "master" en GitHub, resolviendo los conflictos de merge (si fuese necesario).

**Nota**: 7 (Siete)

2024-10-24 18:59 UTC, MVelasquez98 commented on script.js
> +document.querySelector("form").addEventListener("submit", function(event) {
No entra en esta entrega el uso de DOM, estos son los unicos temas de la unidad:
![image](https://github.com/user-attachments/assets/b63fc739-6b00-4bde-8243-0d2929c1af35)
⚠️ Cuidado con el [feature creep](https://www.agile-academy.com/en/agile-dictionary/feature-creep/)

2024-10-24 18:59 UTC, MVelasquez98 commented on script.js
> +    event.preventDefault();
No entra en esta entrega el uso de Eventos, estos son los unicos temas de la unidad:
![image](https://github.com/user-attachments/assets/b63fc739-6b00-4bde-8243-0d2929c1af35)
⚠️ Cuidado con el [feature creep](https://www.agile-academy.com/en/agile-dictionary/feature-creep/)

2024-10-24 18:59 UTC, MVelasquez98 commented on script.js
> +    let inputs = document.querySelectorAll("input");
No entra en esta entrega el uso de DOM, estos son los unicos temas de la unidad:
![image](https://github.com/user-attachments/assets/b63fc739-6b00-4bde-8243-0d2929c1af35)
⚠️ Cuidado con el [feature creep](https://www.agile-academy.com/en/agile-dictionary/feature-creep/)

2024-10-24 18:59 UTC, MVelasquez98 commented on script.js
> +            alert(`El campo ${inputs[i].name} está vacío`);
Ya existen [validaciones](https://developer.mozilla.org/es/docs/Learn/Forms/Form_validation) de campo vacio en HTML5 sin necesidad de usar JS

2024-10-24 18:59 UTC, MVelasquez98 commented on script.js
> +    { nombre: "Hamburguesa Clásica", precio: 8500 },
¿Por qué no definir una [Clase](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Classes) Hamburguesa o Producto? Con sus metodos propios para calcular descuento, etc.

2024-10-24 18:59 UTC, MVelasquez98 commented on script.js
> +    let precioUnitario = 8500;
¿Este precio es estatico?¿Por que no sacarlo del producto que elige el usuario?¿Todos los productos valen lo mismo?

2024-11-08 03:25 UTC, inakitrapiella commented
Hola profesor, ya hice el push con los cambios para arreglar el trabajo, solicito el LGTM para poder seguir con mi trabajo de la nueva entrega.

2024-11-08 03:26 UTC, inakitrapiella commented
@MVelasquez98

2024-11-18 23:42 UTC, inakitrapiella commented
@MVelasquez98

2024-11-19 14:35 UTC, inakitrapiella commented
Hola profe, ahora si creo que deberían estar lo cambios realizados, solicito el LGTM para poder hacerle entrega del trabajo que se entrega hoy

2024-11-19 14:35 UTC, inakitrapiella commented
@MVelasquez98

2024-11-19 14:41 UTC, MVelasquez98 commented
Te falta esta review:

> Las clases se utilizan en un archivo aparte por ejemplo Hamburguesa.js, tal como vimos durante el [encuentro](https://github.com/MVelasquez98/Programaci-n-Web-I---UCES/tree/feature/tercera-entrega/Clase%2009)

2024-11-19 15:01 UTC, inakitrapiella commented
Hola profesor, ya realice un hamburguesa.js aparte espero que el trabajo este bien, solicito lgtm y que tenga una muy linda semana @MVelasquez98

2024-11-19 15:04 UTC, MVelasquez98 commented
Ojo que por error me parece, estas eliminando el uso de arrays (que es correcto) en esta entrega:
![image](https://github.com/user-attachments/assets/b7bd49bc-d3bd-4f42-8863-63cf23577553)

2024-11-19 15:06 UTC, MVelasquez98 commented
Las entradas de datos en esta entrega para la interaccion con el usuario tienen que ser con **prompt**, posteriormente en a entrega 4 reemplazas por el uso de DOM y Eventos.

2024-11-19 15:08 UTC, inakitrapiella commented
Entonces el trabajo esta bien profe o tengo que modificarle algo?
@MVelasquez98

2024-11-19 15:35 UTC, inakitrapiella commented
Recién realice mas cambios profe, agregue prompt e hice los alert.

2024-11-19 15:35 UTC, inakitrapiella commented
@MVelasquez98

2024-11-19 16:42 UTC, MVelasquez98 approved these changes
LGTM

2024-11-19 16:42 UTC, MVelasquez98 commented on script.js
> +        document.getElementById("resultadoCotizacion").textContent = `El precio total es: $${total}`;
Seguis utilizando DOM, no entra en esta entrega. Para esta entrega solo usamos alert, prompt y console.log()

2024-11-19 16:42 UTC, MVelasquez98 commented on script.js
> +
Las clases se utilizan en un archivo aparte por ejemplo `Hamburguesa.js`, tal como vimos durante el [encuentro](https://github.com/MVelasquez98/Programaci-n-Web-I---UCES/tree/feature/tercera-entrega/Clase%2009)

2024-11-19 16:42 UTC, MVelasquez98 commented on script.js
> +class Hamburguesa {
Nunca utilizas la [clase](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Classes) Hamburguesa ¿Para que esta definida?
La idea del cambio es que utilizas este mismo array que habias 
hecho, pero con clases definidas:
<img width="414" alt="image" src="https://github.com/user-attachments/assets/14733d21-352a-475b-b930-fe9d7c66249c">
Por ejemplo:

> const hamburguesas = [
>   new Hamburguesa("Clásica", ["carne", "queso", "lechuga", "tomate"], 5.99, "mediana"),
>   new Hamburguesa("Doble Queso", ["doble carne", "doble queso", "cebolla", "pepino"], 7.99, "grande"),
>   new Hamburguesa("Vegetariana", ["hamburguesa de garbanzos", "lechuga", "aguacate", "tomate"], 6.49, "mediana"),
>   new Hamburguesa("Picante", ["carne", "jalapeños", "queso picante", "salsa especial"], 6.99, "mediana")
> ];

2024-11-20 01:02 UTC, merged