agregue cambios
inakitrapiella/ProgWeb_1 pull request #6
Opened 2024-11-20 01:07 UTC by inakitrapiella

Hola profesor, entrego actividad 4, espero este todo bien saludos.

2024-11-25 05:25 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

- **Funcionalidad (2 puntos)**
✅ 1 punto: Simula uno o más flujos de trabajo en términos de entrada, proceso y salida. 
✅ 1 punto: La funcionalidad es apropiada al contexto del simulador y carece de errores de cómputo durante el procesamiento.

- **Interactividad (2 puntos)**
✅ 1 punto: Captura entradas ingresadas por el usuario mediante eventos.
✅ 1 punto: Efectúa una o más salidas por HTML modificando el DOM, con control de ingreso de entradas y salidas coherentes en relación a los datos ingresados.

- **Escalabilidad (2 puntos)**
✅ 0.5 puntos: Declara funciones con parámetros para definir instrucciones con una tarea específica.
❌ 0 puntos: No emplea arrays para agrupar valores relacionados.
❌ 0 puntos: No define objetos con propiedades y métodos relevantes al contexto. Pensar en utilizar una clase Carrito.
⚠️ 0.25 puntos: Establece un criterio homogéneo para la detección de eventos y almacena en storage datos relevantes generados durante la simulación. Pensar en que hacer con esa orden almacenada en el storage ¿ qué pasa si cancelo una orden? ¿ y si quiero hacer más de una? Poder visualizar esa orden en algún lado en el DOM.

- **Integridad (1 punto)**
✅ 0.5 puntos: Define el código JavaScript en un archivo .js, referenciándolo correctamente desde el HTML.
❌ 0 puntos: No evita métodos prompt() y alert() para evitar interrupciones durante el procesamiento y actualización del DOM.

- **Legibilidad (1 punto)**
✅ 0.5 puntos: Los nombres de variables, funciones y objetos son significativos para el contexto.
⚠️ 0.25 puntos: Las instrucciones se escriben de forma legible y se emplean comentarios oportunos, manteniendo el código fuente ordenado en términos de declaración y secuencia. En algún punto el código hace demasiadas cosas, considero que con la clase `Carrito.js` se va solucionar.

- **GitHub (2 puntos):**
✅ 0.5 puntos: Realización de commits necesarios sobre la rama de desarrollo utilizando Git.
❌ 0 puntos: Creación de una rama "feature/cuarta-entrega" a partir de la rama "develop" utilizando Git. Cuidado que la rama marca este aviso `This branch is [7 commits ahead of](https://github.com/inakitrapiella/ProgWeb_1/tree/feature/cuarta-entrega) master.` No queda nada más que verificar la proxima desde donde se parte el origen de la rama para crear otra.
✅ 1 punto: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "feature/tercera-entrega" con "develop" en GitHub. 

**Nota: 8(ocho)**

2024-11-25 05:25 UTC, MVelasquez98 commented on script.js
> -import { Hamburguesa } from './Hamburguesa';
¿Por qué eliminas el uso de la clase Hamburguesa? Sigue siendo necesaria

2024-11-25 05:25 UTC, MVelasquez98 commented on script.js
> +function guardarOrden() {
Usar una clase para el carrito u orden: Implementa una clase para encapsular la lógica del carrito u orden. Esto mejora la reutilización y la claridad. Por ejemplo:

```
class Carrito {
    constructor() {
        this.productos = JSON.parse(localStorage.getItem("carrito")) || [];
    }

    guardar() {
        localStorage.setItem("carrito", JSON.stringify(this.productos));
    }

    agregar(nombre, precio) {
        if (!esProductoValido(nombre, precio)) return;
        // Lógica de agregar...
    }

    // Otras funciones...
}

```

2024-11-25 05:25 UTC, MVelasquez98 commented on script.js
> +    alert("Orden guardada exitosamente.");
Aunque el uso de alert es útil, puede causar una mala experiencia de usuario. Considera mostrar los mensajes de error en el formulario en lugar de usar ventanas emergentes. Podes incluso usar [modales](https://getbootstrap.com/docs/4.1/components/modal/), o hasta animarte a usar alguna lib de js como [SweetAlert](https://sweetalert2.github.io/)

2024-11-25 05:25 UTC, MVelasquez98 commented on script.js
> +        alert("Por favor, calcula el precio antes de guardar la orden.");
Aunque el uso de alert es útil, puede causar una mala experiencia de usuario. Considera mostrar los mensajes de error en el formulario en lugar de usar ventanas emergentes. Podes incluso usar [modales](https://getbootstrap.com/docs/4.1/components/modal/), o hasta animarte a usar alguna lib de js como [SweetAlert](https://sweetalert2.github.io/)

2024-11-25 05:25 UTC, MVelasquez98 commented on script.js
> -const menu = [
¿Por qué eliminaste el uso de arrays? Es necesario

2024-11-25 05:25 UTC, MVelasquez98 commented on script.js
> +    const tipoHamburguesa = document.getElementById("tipoHamburguesa");
No se verifica si los valores ingresados por el usuario son válidos antes de realizar el cálculo, lo que puede provocar NaN en el total. Validar que tipoHamburguesa y cantidad sean números antes de realizar el cálculo.

2024-11-25 05:25 UTC, MVelasquez98 commented on script.js
> +    const nombre = document.getElementById("nombre").value;
El código no verifica que los campos nombre y email sean válidos antes de capturar o guardar datos. Esto puede resultar en guardar datos incompletos o incorrectos.

2024-11-25 16:14 UTC, inakitrapiella commented
Hola profesor, le quiero comunicar que ya realice los cambios que solicito y me gustaria solicitarle el LGTM para poder realizar la entrega de mi parcial. @MVelasquez98

2024-11-25 18:06 UTC, MVelasquez98 commented
No se si es correcto un comportamiento en donde pueda agregar cualquier producto a cualquier precio ¿no deberia estar pre configurado esto?
![image](https://github.com/user-attachments/assets/51f1020b-d109-4fa2-bd13-d1a033f53fdf)
Por otro lado, ya no puedo realizar la simulación de cotización:
![image](https://github.com/user-attachments/assets/2025eab5-6dfd-43cb-a24f-2141d4e4c92a)

2024-11-25 20:21 UTC, inakitrapiella commented
Hola profesor ahora si ya deberia estar todo funcionando correctamente, espero este asi y solicito el LGTM para la realizacion del parcial. @MVelasquez98

2024-11-26 02:09 UTC, MVelasquez98 commented
Revisar comentarios

2024-11-26 02:20 UTC, inakitrapiella commented
Hola profesor, aca esta el uso de arrays y de la clase hamburguesa 
![Captura de pantalla 2024-11-25 231732](https://github.com/user-attachments/assets/2fb27608-944f-412c-ab92-fbc84217ae4b)
![Captura de pantalla 2024-11-25 231919](https://github.com/user-attachments/assets/ad9958fd-3b4a-4707-a215-bba364411cba)

2024-11-26 02:20 UTC, inakitrapiella commented
@MVelasquez98

2024-11-26 02:30 UTC, MVelasquez98 commented
Pero no lo usas nunca, no esta importado, estas definiendo un array de objetos. No un array de la clase hamburguesa. Por ejemplo:
```
const menuHamburguesas = [
  new Hamburguesa("Clásica", ["Carne", "Lechuga", "Tomate", "Queso"], 5.99, false),
  new Hamburguesa("Vegetariana", ["Tofu", "Lechuga", "Tomate", "Queso"], 6.99, true),
  new Hamburguesa("BBQ", ["Carne", "Cebolla caramelizada", "Queso cheddar", "Salsa BBQ"], 7.99, false),
];
```
Por otro lado, no justifica un archivo aprte Menu.js que solo tenga un array de objetos. Esto tiene que estar en el script.js

2024-11-26 16:28 UTC, inakitrapiella commented
Hola profesor, buenos días le quería comunicar que agregues arrays a mi script, espero este bien :)   @MVelasquez98 , y si esta todo bien solicitaría el lgtm para poder realizar mi parcial.

2024-11-26 16:55 UTC, MVelasquez98 commented
Sigo viendo el Menu.js que no corresponde porque solo tiene un array, y seguis sin usar la clase Hamburguesa.js en el array:
![image](https://github.com/user-attachments/assets/ff76658a-2bb1-491e-8cc0-52f7f458f819)
La diferencia de usar la clase:
```
const menuHamburguesas = [
  new Hamburguesa("Clásica", ["Carne", "Lechuga", "Tomate", "Queso"], 5.99, false),
  new Hamburguesa("Vegetariana", ["Tofu", "Lechuga", "Tomate", "Queso"], 6.99, true),
  new Hamburguesa("BBQ", ["Carne", "Cebolla caramelizada", "Queso cheddar", "Salsa BBQ"], 7.99, false),
];
```
Esto tiene que estar en el script.js directamente

2024-11-26 18:38 UTC, inakitrapiella commented
Hola profesor, ahora creo que si estaría,  elimine menu.js y lo implemente en el script y debería estar usándose la clase hamburguesa.js también. @MVelasquez98

2024-11-26 18:50 UTC, MVelasquez98 commented
Revisar comentarios

2024-11-26 18:54 UTC, inakitrapiella commented
Me aparecen dos comentarios nomas profe, los arrays que implemente en el script y lo de la clase hamburguesa que ya lo esta implementando si es que esta bien, no se si es eso o alguno que no me esta apareciendo.   @MVelasquez98

2024-11-26 18:57 UTC, MVelasquez98 commented
Este comentario en pending:
![image](https://github.com/user-attachments/assets/e99f3da4-71c4-4913-838d-f4ca84e290a0)
Siempre tenes que revisar en [files changed ](https://github.com/inakitrapiella/ProgWeb_1/pull/6/files)que no hay ningun comentario de revision. 
Si te aparece este simbolo es que todavía tenes que resolver cambios:
![image](https://github.com/user-attachments/assets/fd26307a-8e03-4a1e-81e3-4e38d50a4860)

2024-11-26 19:00 UTC, inakitrapiella commented
Buenísimo profe, no lo había visto lo arreglo y se lo envió ya completado. muchas gracias :)

2024-11-26 21:02 UTC, inakitrapiella commented
Hola profe, ya modifique el array e integre el id en la clase hamburguesa. espero este bien :). @MVelasquez98

2024-11-26 23:34 UTC, MVelasquez98 approved these changes
LGTM

2024-11-26 23:34 UTC, MVelasquez98 commented on Menu.js
> +    { id: 1, nombre: "Hamburguesa Clásica", precio: 8500 },
Aca tendrias que usar la clase Hamburguesa.js para hacer un array de la clase Hamburguesa, no simples objetos

2024-11-26 23:34 UTC, MVelasquez98 commented on Menu.js
No justifica un Menu.js que solo tenga un array de objetos. Esto tiene que estar en el script.js

2024-11-26 23:34 UTC, MVelasquez98 commented on script.js
> +    { id: 1, nombre: "Hamburguesa Clásica", precio: 8500 },
Esto es un array de objetos❌::
```
const menuHamburguesas = [
    { id: 1, nombre: "Hamburguesa Clásica", precio: 8500 },
    { id: 2, nombre: "Hamburguesa Texana", precio: 9500 },
    { id: 3, nombre: "Hamburguesa de Queso", precio: 10000 },
    { id: 4, nombre: "Hamburguesa Vegana", precio: 12000 },
];
```
Esto es un array de la clase Hamburguesa ✅:

```
const menuHamburguesas = [
  new Hamburguesa(1, "Hamburguesa Clásica", 8500),
  new Hamburguesa(2, "Hamburguesa Texana", 9500),
  new Hamburguesa(3, "Hamburguesa de Queso", 10000),
  new Hamburguesa(4, "Hamburguesa Vegana", 12000),
];
```

¿Se ve la diferencia? En una haces uso del método constructor de la clase y en el otro no, simplemente es un objeto x

Si te fijas en la definición que hiciste de Hamburguesa no tenes definido el campo "id", pero como no estas usando la clase, no te genera error:
```
class Hamburguesa {
    constructor(nombre, precio) {
    this.nombre = nombre;
    this.precio = precio;
    }
}

export default Hamburguesa;
```

2024-11-28 21:57 UTC, merged