Release/segundo parcial
inakitrapiella/ProgWeb_1 pull request #7
Opened 2024-11-28 22:22 UTC by inakitrapiella

2024-11-29 00:44 UTC, inakitrapiella commented
![Captura de pantalla 2024-11-28 214303](https://github.com/user-attachments/assets/36f98cf7-00d4-458e-93ae-2ecec5bb8218)
![Captura de pantalla 2024-11-28 214342](https://github.com/user-attachments/assets/3fba2535-7ff4-4d0b-9dba-b1651999b4d9)

2024-11-30 18:54 UTC, MVelasquez98 commented
No corresponde subir cambios adicionales, una vez cerro el plazo de entrega en el campus

2024-11-30 18:56 UTC, inakitrapiella commented
Hola profesor, elcambio fue que lo etiquete a usted por que no sabia si lo podia ver. @MVelasquez98

2024-11-30 18:57 UTC, inakitrapiella commented
No por otra cosa no toque nada del codigo ni nada solo fue etiquetarlo

2024-11-30 18:58 UTC, MVelasquez98 commented
La pull request tiene que estar abierta para poder corregir ¿por qué esta cerrada?

2024-11-30 18:59 UTC, inakitrapiella commented
Usted la cerro profe

2024-11-30 18:59 UTC, inakitrapiella commented
@MVelasquez98

2024-11-30 19:00 UTC, inakitrapiella commented
![Captura de pantalla 2024-11-30 160006](https://github.com/user-attachments/assets/72aca29c-05d1-4503-93c5-1d3bbd687be4)

2024-12-01 21:03 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA**:
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

- **Asincronía y Manejo de Datos (3 puntos)**
✅ 1 punto: Utiliza AJAX y JSON para obtener datos de forma asíncrona, manejando adecuadamente promises y fetch para consumir alguna API mock .
❌ 0 puntos: Todavía hay información estática que no esta en formato JSON, y no se carga y utiliza de manera asíncrona.
✅ 1 punto: Recorrido de colecciones siendo óptimo utilizando funciones de orden superior. 

- **Gestión del Proyecto y Buenas Prácticas con GitHub (7 puntos)**:
✅ 1 punto: Realización de commits necesarios sobre la rama de desarrollo utilizando Git.
✅ 1 punto: Creación de una rama release/segundo-parcial a partir de la rama develop utilizando Git.
✅ 1 punto: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama feature/cuarta-entrega con develop en GitHub.
✅ 1 punto: Proporcionar la URL de la pull request y la URL generada por GitHub Pages para la rama release/segundo-parcial como parte de la entrega.
⚠️ 0.5 puntos: Implementa un archivo [CHANGELOG.md](https://github.com/Laboratoria/changelog-guide) documentando los cambios realizados en el proyecto en cada entrega o versión, siguiendo un formato estructurado. Revisa cambios propuestos, aún esta incompleto.
✅ 1 punto: Configura [reglas en GitHub](https://docs.github.com/es/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule) para bloquear push directos a las ramas develop y master, exigiendo pull requests con al menos un revisor aprobado para realizar merges. Incluir en el comentario de la pull request una captura con el estado de las reglas.
⚠️ 0.5 puntos: Implementa una [plantilla (template) de pull request](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) en el repositorio para estandarizar las solicitudes de revisión y asegurarse de incluir in[formación relevante](https://axolo.co/blog/p/part-3-github-pull-request-template) (descripción, cambios realizados, pruebas realizadas, etc.).  Agregar más detalles al respecto, tomar como modelo el ejemplo proporcionado

**Nota**: 8(Ocho)

**Comentarios**:  Hiciste un buen progreso hasta ahora, y se nota el esfuerzo puesto en el proyecto. Sin embargo, hay áreas clave que requieren atención y mejora antes de la entrega final. Aca te dejo algunas recomendaciones finales:

- Asincronía y Manejo de Datos:
Aún queda pendiente trabajar sobre la carga asíncrona de toda la información estática desde archivos JSON. Esto no solo optimiza el rendimiento de la aplicación, sino que también cumple con las mejores prácticas de desarrollo moderno. Intenta convertir más componentes de tu aplicación para funcionar con JSON cargado dinámicamente y asíncronamente.

- Gestión del Proyecto y Buenas Prácticas con GitHub:
- CHANGELOG: Asegúrate de que tu CHANGELOG.md esté bien estructurado y detallado, reflejando todos los cambios en cada versión. Esto te beneficia al mantener un historial claro de las mejoras y correcciones realizadas.
Reglas de Protección y Flujos en GitHub: Es crucial configurar las reglas para proteger las ramas principales (develop y master) y requerir revisiones para las pull requests. Esto asegura que el código se desarrolle de manera colaborativa y segura.
- Plantillas de Pull Request: Implementa una plantilla de pull request para estandarizar la documentación y revisión de cambios. Esto facilitará la colaboración en equipo y asegurará que la información crítica esté siempre documentada.

- Enfoque en el Simulador: Parece que algunas características están un poco desconectadas del objetivo principal. Por ejemplo, no hay ningun boton para finallizar compra, por un lado se calcula el precio de la orden, por otro se arma un carrito, y por otro lado hay otros productos que no estan en el menu inicial. Es importante que tu implementación sea coherente y que todas las piezas trabajen juntas en función del objetivo del simulador. Recomendación: Define claramente el propósito del simulador y revisa el diseño para asegurar que todos los componentes interactúen de manera significativa.

Si te concentras en estos aspectos no solo mejorará la calidad de tu proyecto, sino que también te ofrecerá la confianza necesaria para presentar y defender tu trabajo de manera efectiva durante el examen final. ¡Continúa con el gran esfuerzo y exitos!

2024-12-01 21:03 UTC, MVelasquez98 commented on TEMPLATE.md
No esta bien agregado, tiene que estar dentro de la carpeta github y tener el nombre de archivo correcto, la idea es que esta plantilla, si esta bien configurada, te aparezca cada vez que haces una pull request para rellenar. PAra lograr eso, tiene que tener el nombre de archivo correcto y estar en la carpeta github en el proyecto

2024-12-01 21:03 UTC, MVelasquez98 commented on Changelog.md
Ordenalo por las fechas y entregas reales que hiciste en el proyecto:
Actividad obligatoria N°1
Actividad obligatoria N°2
Actividad obligatoria N°3
Actividad obligatoria N°4
Primer Parcial
Segundo Parcial

2024-12-01 21:03 UTC, MVelasquez98 commented on TEMPLATE.md
Incluí más puntos de control, si soy tu jefe, tu compañero, esta es la documentación breve que me presentas de que es lo que estas trabajando y ahora antregas, mira este template, solo a modo de ejemplo:
```
<!--- Provide a general summary of your changes in the Title above -->

<!-- Check and try your best to make your commits follow the guidelines explained in https://chris.beams.io/posts/git-commit/ -->

## Description

<!--- Describe your changes in detail -->

## Motivation and Context

<!--- Why is this change required? What problem does it solve? -->
<!--- If it fixes an open issue, please link to the issue here. -->

## Types of changes

<!--- What types of changes does your code introduce? Put an `x` in all the boxes that apply: -->
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

<!--- Go over all the following points, and replace `[ ]` with `[x]` in all the boxes that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->
- [ ] My code follows the [code style](https://github.com/mercadolibre/fury_go-toolkit/blob/master/STYLE.md) of this project.
- [ ] My commits follow as good as possible the guidelines indicated in [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/).
- [ ] My Pull Request follows the [Contribution and Pull Requests Etiquette](https://github.com/melisource/fury_acq-parameterstore-api/blob/develop/CONTRIBUTE.MD).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly (if applicable).
- [ ] I have updated the CHANGELOG.
- [ ] I have tested in Fury (if apply).
```

2024-12-01 21:03 UTC, MVelasquez98 commented on script.js
> +const menuHamburguesas = [
Esta informacion estatica tiene que estar en un JSON 
`api/productos.json`

2024-12-01 21:03 UTC, MVelasquez98 commented on Changelog.md
Linkea las Pull request

2024-12-01 21:10 UTC, MVelasquez98 commented
Parecen 4 procesos aislados independientes, ¿no puede unificarse la vista del menu para escoger que productos agregar al carrito y ahi calcular el precio? Para que tenga coherencia el simulador:
![image](https://github.com/user-attachments/assets/b68a8572-4bfe-410f-8987-a0e8807f9cd9)

2025-07-24 16:04 UTC, inakitrapiella commented
@MVelasquez98  solicito LGTM

2025-07-24 17:31 UTC, MVelasquez98 commented
> Parecen 4 procesos aislados independientes, ¿no puede unificarse la vista del menu para escoger que productos agregar al carrito y ahi calcular el precio? Para que tenga coherencia el simulador: ![image](https://private-user-images.githubusercontent.com/43156596/391363366-b68a8572-4bfe-410f-8987-a0e8807f9cd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMzNzgzNjQsIm5iZiI6MTc1MzM3ODA2NCwicGF0aCI6Ii80MzE1NjU5Ni8zOTEzNjMzNjYtYjY4YTg1NzItNGJmZS00MTBmLTg5ODctYTBlODgwN2Y5Y2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzI0VDE3Mjc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMWI3YTk1ZTRkZGY2ZTk2OTA0OGZiZTk1NTFkNTIyZjk3NjdhODM4ZDcyYmZkZTMyMzNjODlhN2M5NWI0OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zVMfy7UXa8SFdIxLpwXboGx6_Dzx218DZXf8U0ywWKg)

Todavía te falta resolver este comentario, no es un simulador completo, son procesos aislados.

2025-07-24 17:56 UTC, inakitrapiella commented
Solucionado profe @MVelasquez98

2025-07-24 18:01 UTC, MVelasquez98 commented
<img width="856" height="113" alt="image" src="https://github.com/user-attachments/assets/77b20f0b-ce43-46e3-bae9-4db674c49a62" />
<img width="577" height="141" alt="image" src="https://github.com/user-attachments/assets/22753a34-8d5e-4871-ac19-1b6a30529c30" />
Tenes errores en consola

2025-07-24 18:04 UTC, inakitrapiella commented
Hola profe, a mi no me aparece el error. Como puedo solucionarlo?  @MVelasquez98 
<img width="1862" height="1027" alt="Captura de pantalla 2025-07-24 150356" src="https://github.com/user-attachments/assets/7e055cd5-91f3-41c2-9a5c-3f48aba4627b" />

2025-07-24 18:05 UTC, MVelasquez98 commented
<img width="866" height="247" alt="image" src="https://github.com/user-attachments/assets/5ae428f2-2622-418e-9261-aa090ba9ea6f" />
No estas haciendo uso del [LocalStorage](https://developer.mozilla.org/es/docs/Web/API/Window/localStorage) para almacenar o capturar valores del navegador

2025-07-24 18:18 UTC, inakitrapiella commented
@MVelasquez98 

Listo profesor, lo use para guardar el carrito del usuario por mas que salga de la web, espero este bien profe. 

Gracias

2025-07-24 18:31 UTC, MVelasquez98 requested changes
<img width="562" height="649" alt="image" src="https://github.com/user-attachments/assets/214f4512-ed0d-4f2c-9ed4-c01561e2282b" />
Hay errores en el simulador, no esta calculando correctamente el total de los productos existentes en el carrito

2025-07-24 18:54 UTC, inakitrapiella commented
@MVelasquez98 

Hola profe, ya arregle el guardar orden, espero este bien, gracias.

2025-07-24 19:02 UTC, MVelasquez98 requested changes
La conexion a la API para nuevos ingresos sigue sin funcionar:
<img width="1436" height="776" alt="image" src="https://github.com/user-attachments/assets/04b32471-b77a-4b0d-ac3b-8f1e95741859" />
Quedan en pending todas las pegadas a la AP, despues de un rato dan error. Probe con el CORS habilitado y deshabilitado y es lo mismo:
<img width="1438" height="755" alt="image" src="https://github.com/user-attachments/assets/188ab436-b989-4a37-a423-8437d1845146" />

2025-07-24 19:06 UTC, inakitrapiella commented
@MVelasquez98 

Hola profe a mi no me aparecen errores, probé desde mi pc y la de mis papas y no me aparece ningún error, no se a que se debe, le adjunto captura.

<img width="1862" height="1030" alt="image" src="https://github.com/user-attachments/assets/4368782d-7e57-4023-8371-97d9d2b272c7" />

gracias profe.

2025-07-24 19:15 UTC, MVelasquez98 requested changes

2025-07-24 19:15 UTC, MVelasquez98 commented on .github/PULL_REQUEST_TEMPLATE.md
El nombre del archivo tiene que ir en minuscula `.github/pull_request_template.md`, solo la carpteta contenedora va en mayuscula, en caso de que tengas más de un template. Revisa la [documentación](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository).
Si esto esta bien configurado, ya en esta pull request deberias utilizar este template

2025-07-24 19:22 UTC, inakitrapiella commented
Listo profesor 

@MVelasquez98

2025-07-24 19:27 UTC, MVelasquez98 approved these changes
LGTM

2025-07-24 19:31 UTC, merged